name: konvertr_free
description: Unit Converter App built using Flutter

version: 0.8.5+21

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  animations: ^2.0.0
  another_flushbar: ^1.10.18
  flutter_translate: ^3.0.1
  flutter_translate_annotations: ^2.0.0
  package_info: ^2.0.0
  provider: ^5.0.0
  url_launcher: ^6.0.3

dev_dependencies:
  build_runner: ^2.0.1
  flutter_translate_gen: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/units.json
    - assets/i18n/
  fonts:
    - family: KonvertrIcons
      fonts:
        - asset: assets/fonts/KonvertrIcons.ttf