name: konvertr_free
description: Unit Converter App built using Flutter

version: 0.7.3+13

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  animations: ^1.1.1
  flushbar: ^1.10.4
  flutter_clipboard_manager: ^0.0.2
  flutter_translate: ^1.6.0
  flutter_translate_annotations: ^1.0.0
  provider: ^4.3.1

dev_dependencies:
  build_runner: ^1.10.2
  flutter_translate_gen: ^1.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/data/units.json
    - assets/i18n/
  fonts:
    - family: KonvertrIcons
      fonts:
        - asset: assets/fonts/KonvertrIcons.ttf