name: konvertr
description: Unit Converter App built using Flutter

version: 0.0.1+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clipboard_manager: ^0.0.2
  flutter_icons: ^1.1.0
  get: ^2.11.0
  google_fonts: ^1.1.0
  provider: ^4.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/data/units.json