name: konvertr_free
description: Unit Converter App built using Flutter

version: 0.5.0+7

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  animations: ^1.1.1
  flushbar: ^1.10.4
  flutter_clipboard_manager: ^0.0.2
  flutter_icons: ^1.1.0
  provider: ^4.1.3+1

flutter:
  uses-material-design: true
  assets:
    - assets/data/units.json