name: konvertr
description: Unit Converter App built using Flutter

version: 1.1.1+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^4.0.5+1
  page_transition: ^1.1.5

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/data/units.json
