name: konvertr_free
description: Unit Converter App built using Flutter

version: 0.2.1+4

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  animations: ^1.1.1
  flutter_clipboard_manager: ^0.0.2
  flutter_icons: ^1.1.0
  get: ^2.14.1
  provider: ^4.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/data/units.json